datalabel/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='login'),
    path('index', views.index, name='login'),
    path('notice', views.notice, name='notice'),
    path('jiaocheng', views.jiaocheng, name='jiaocheng'),
    path('task_detail', views.task_detail, name='task_detail'),
    path('notice_info', views.notice_info, name='notice_info'),
    path('login', views.login, name='login'),
    path('admin_login', views.admin_login, name='admin_login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('comment', views.comment, name='comment'),
    path('creator/', include('creator.urls')),
    path('worker/', include('worker.urls')),
    path('service/', include('service.urls')),
    path('finance/', include('finance.urls')),
    path('manager/', include('manager.urls')),
    path('admin/', admin.site.urls),
]

service/urls.py
from django.urls import path
from . import views
from . import admin
app_name='service'

urlpatterns = [
	path('', views.index, name="index"),
	path('<str:sId>/index', views.index, name="index"),
	path('<str:sId>/task_list', views.task_list, name="task_list"),
	path('<str:sId>/<int:taskId>/check', views.check, name="check"),
	path('<str:sId>/task_info', views.task_info, name="task_info"),
	path('<str:sId>/<int:pId>/handle', views.handle, name="handle"),
	path('<str:sId>/<str:taskId>/labelResultView', views.labelResultView, name="labelResultView"),
	path('<str:sId>/<str:taskId>/getlink/', views.getlink),
]

worker/urls.py
from django.urls import path
from . import views
from . import admin
app_name='worker'

urlpatterns = [
	path('<str:name>/', views.index, name="index"),
	# path('index', views.index, name='index'),
	path('<str:name>/index', views.index, name='index'),
	path('<str:name>/info', views.info, name='info'),
	path('<str:name>/task_list', views.task_list, name='task_list'),
	path('<str:name>/charts', views.charts, name='charts'),
	path('<str:name>/other_info', views.other_info, name="other_info"),
	path('<str:name>/task_info', views.task_info, name="task_info"),
	path('<str:name>/task_accept', views.task_accept, name="task_accept"),
	path('<str:name>/task_submit', views.task_submit, name="task_submit"),
	path('<str:name>/task_abandon', views.task_abandon, name="task_abandon"),
	path('<str:name>/labelTry', views.labelTry, name="labelTry"),
	path('<str:name>/problem_create', views.problem_create, name="problem_create"),
	path('<str:name>/label', views.label, name="label"),
	path('<str:name>/getlink/', views.getlink),
]

service/models.py
from django.db import models
from creator import models as cmodels
from worker import models as wmodels
from manager import models as mmodels
# Create your models here.


class problem(models.Model):
    pId = models.AutoField(primary_key=True)
    pName = models.CharField(max_length=40, null=True)
    cId = models.ForeignKey(cmodels.creator, to_field='cId', on_delete=models.CASCADE, null=True)
    wId = models.ForeignKey(wmodels.worker, to_field='wId', on_delete=models.CASCADE, null=True)
    staffId = models.ForeignKey(mmodels.staff, to_field='staffId', on_delete=models.CASCADE)
    taskId = models.ForeignKey(cmodels.task, related_name="staskId", to_field="taskId", on_delete=models.CASCADE, null=True)
    pContent = models.TextField()
    subTime = models.DateTimeField()
    statuss = (
        ('unHandle', '未处理'),
        ('handled', '已处理')
    )
    types = (
        ('taskResult', "任务审核结果申诉"),
        ('taskReward', "任务奖励发放申诉"),
        ('account', "个人账户信息申诉"),
        ('labelSystem', "标注系统异常申诉"),
    )
    type = models.CharField(choices=types, null=True, max_length=20)
    status = models.CharField(choices=statuss, max_length=20)
    feedBack = models.TextField(null=True)
    choice = (
        ('unpunish', '不处罚'),
        ('punish', '处罚'),
        ('compensate', '补偿')
    )
    punish = models.CharField(choices=choice, null=True, max_length=20)
    finTime = models.DateTimeField(null=True)


class release_task_check(models.Model):
    taskId = models.ForeignKey(cmodels.task, to_field='taskId', on_delete=models.CASCADE)
    staffId = models.ForeignKey(mmodels.staff, to_field='staffId', on_delete=models.CASCADE, null=True)
    subTime = models.DateTimeField()
    results = (
        ('pass', '通过'),
        ('unpass', '未通过')
    )
    checkResult = models.CharField(choices=results, null=True, max_length=20)
    feedBack = models.TextField(null=True)
    finTime = models.DateTimeField(null=True)

service/views.py
import base64
import datetime
import io
import zipfile
from itertools import chain

import pandas as pd
from django.shortcuts import render, redirect
from service import models as smodels
from creator import models as cmodels
from finance import models as fmodels
from worker import models as wmodels
from manager import models as mmodels
from django.http import HttpResponse
import json

# Create your views here.
def index(request, sId):
    sId = mmodels.staff.objects.get(staffId=sId).staffId
    problems = smodels.problem.objects.filter(staffId_id = sId)
    return render(request, "service/index.html", {'problems':problems, 'sId':sId})

def task_list(request, sId):
    sId = mmodels.staff.objects.get(staffId=sId).staffId
    problems = smodels.problem.objects.filter(staffId_id = sId, status='unHandle')
    rctasks = smodels.release_task_check.objects.filter(staffId_id=sId, checkResult__isnull=True)
    for rctask in rctasks:
        tmp_task = cmodels.task.objects.get(taskId=rctask.taskId_id)
        rctask.taskName = tmp_task.taskName
        rctask.taskContent = tmp_task.taskContent
        rctask.taskLimit = tmp_task.taskLimit
        rctask.taskType = tmp_task.get_taskType_display()
        rctask.status = tmp_task.get_status_display()
        rctask.type = "rctask"
        rctask.cName = cmodels.creator.objects.get(cId=tmp_task.cId_id).name
    for problem in problems:
        problem.type = "problem"
        try:
            problem.name = cmodels.creator.objects.get(cId=problem.cId_id).name
        except:
            problem.name = wmodels.worker.objects.get(wId=problem.wId_id).name
    taskAll = list(chain(problems, rctasks))
    taskAll = sorted(taskAll, key=lambda x:x.subTime, reverse=True)
    return render(request, "service/task_list.html", {'taskAll':taskAll, 'rctask':rctasks, 'problem':problems, 'sId':sId})

def get_taskInfo(taskId):
    task = cmodels.task.objects.get(taskId=taskId)
    data = cmodels.data.objects.filter(taskId_id=task.taskId)
    # Excel文件预览处理
    datas = []
    if data[0].dType == 'word':
        with io.BytesIO(data[0].dFile) as f:
            with zipfile.ZipFile(f, 'r') as zfile:
                fname = zfile.namelist()[0]
                print(fname)
                with zfile.open(fname, mode='r') as tfile:
                    try:
                        tdata = pd.read_excel(tfile, header=None)
                    except:
                        tdata = pd.read_csv(tfile, header=None, error_bad_lines=False)
        count = 0
        for i in range(tdata.shape[0]):
            if count < 10:
                datas.append(list(tdata.iloc[i, :]))
                count += 1
            else:
                break
    elif data[0].dType == "pic":
        for temp in data:
            datas.append(base64.b64encode(temp.dFile).decode('utf8'))
    return task, data, datas

def task_info(request, sId):
    taskId = request.GET.get('taskId')
    task, data, datas = get_taskInfo(taskId)
    pId = request.GET.get('pId')
    return redirect(f"/service/{sId}/{pId}/handle", {'task': task, 'sId': sId, 'datas': datas, 'data': data[0]})

def check(request, sId, taskId):
    '''
    进入待发布任务的check页面
    '''
    if request.method=="GET":
        # sId = smodels.staff.objects.get(n).sId
        type = request.GET.get('type')
        task, data, datas = get_taskInfo(taskId)
        return render(request, "service/check.html", {'task':task, 'sId':sId, 'datas':datas, 'data':data[0]})
    elif request.method=="POST":
        taskId = request.POST.get('taskId')
        rctask = smodels.release_task_check.objects.get(taskId_id=taskId)
        task = cmodels.task.objects.get(taskId=taskId)
        # 任务审核结果添加
        check_result = request.POST.get('pass')
        if check_result=="unpass":
            rctask.checkResult = 'unpass'
            feed_back = request.POST.get('feed_back')
            task.status = 'unpass'
            rctask.feedBack = feed_back
        else:
            rctask.checkResult = "pass"
            task.status = 'unAccept'
        task.save()
        rctask.finTime = datetime.datetime.now()
        rctask.save()
        return redirect(f'/service/{sId}/task_list')


def handle(request, sId, pId):
    sId = mmodels.staff.objects.get(staffId=sId).staffId
    if request.method=="GET":
        # sId = smodels.staff.objects.get(n).sId
        type = request.GET.get('type')
        problem = smodels.problem.objects.get(pId=pId)
        task, data, datas = get_taskInfo(problem.taskId_id)
        return render(request, "service/handle.html", {'problem':problem, 'task':task, 'sId':sId, 'datas':datas, 'data':data[0]})
    elif request.method=="POST":
        pId = request.POST.get('pId')
        feedBack = request.POST.get('feedBack')
        # 添加申诉处理结果
        problem = smodels.problem.objects.get(pId=pId)
        problem.status = 'handled'
        problem.feedBack = feedBack
        problem.finTime = datetime.datetime.now()
        problem.save()
        # 添加惩罚或补偿
        punish = request.POST.get('punish')
        # 获取惩罚或补偿金额
        punishSum = request.POST.get('punishSum') if request.POST.get('punishSum') else 0
        # 如果存在积分处罚，则需要添加积分任务
        if punishSum:
            new_pointTask = fmodels.point(
                trasaction=punishSum,
                status='punish' if punish=="punish" else "compensate",
                pDate=datetime.datetime.now(),
                cId_id=cmodels.task.objects.get(taskId=problem.taskId_id, deleted=0).cId_id,
                staffId_id=problem.staffId_id,
                taskId_id=problem.taskId_id,
                wId_id=wmodels.acceptedTask.objects.get(taskId_id=problem.taskId_id, delete=0).wId_id,
                type='punish' if punish=="punish" else "compensate",
                # 与申诉连接起来
                pId_id=problem.pId
            )
            new_pointTask.save()
        # 为财务工作人员提交需要处罚的申诉内容
        # 选择当前工作最少的进行任务添加
        punishs = fmodels.punish.objects.all()
        financers = mmodels.staff.objects.filter(staffType='F', staffStatus='A', deleted=0)
        distribution = {}
        for financer in financers:
            distribution[financer] = len(punishs.filter(staffId_id=financer.staffId))
        distribution = sorted(distribution.items(), key=lambda x:x[1])
        fId = distribution[0][0].staffId
        new_punish = fmodels.punish(
            staffId_id=fId,
            pId_id=pId,
            punishSum=punishSum,
            status="unHandle"
        )
        new_punish.save()
        return redirect(f'/service/{sId}/task_list')


def labelResultView(request, sId, taskId):
    # 进入任务标注结果查界面
    label_url = "/service/" + sId + "/" + taskId
    pId = request.GET.get('pId')
    if request.method == "GET":
        # taskId_ano = request.GET.get('taskId')
        lenth_of_imgs = len(cmodels.data.objects.filter(taskId_id=int(taskId)))
        lenth_of_labels = len(wmodels.labels.objects.filter(taskId_id=taskId))
        print(lenth_of_labels)
        if lenth_of_labels==0:
            data = {"lenth": lenth_of_imgs,
                    "index_now": 1,
                    "taskId_ano":taskId,
                    "label_url":label_url,
                    "identity":"service",
                    }
        else:
            data={"lenth":lenth_of_imgs,
                  "index_now":lenth_of_labels,
                  "taskId_ano":taskId,
                  "label_url": label_url,
                  "identity": "service",
                  }
        return render(request, "index_ano.html", {"init_data": data, 'pId':pId, 'name':sId, 'userType':'service', 'taskId':taskId})
    elif request.method == "POST":
        print("You are not allowed to change the data!")
    else:
        return HttpResponse()


def getlink(request,  sId, taskId):
    index = request.GET.get("index")  # 项目中的图片的index，还需要知道图片的真正的index
    # taskid_ano=request.GET.get("taskid_ano")
    obj_lis = cmodels.data.objects.filter(taskId_id=int(taskId))
    # map_dic结构如下：{index:true_index}
    # map_dic={}
    # for temp_index in range(len(obj_lis)):
    #     map_dic[str(temp_index)]=obj_lis[temp_index]["id"]
    obj = obj_lis[int(index) - 1]
    img = obj.dFile
    true_id = obj.dId
    # img = Image.open(io.BytesIO(img))
    # img_array = np.asarray(img)
    # print(img_array.shape)
    # buffer = BytesIO()
    # img.save(buffer, format='PNG')  # 将PIL Image对象转化为PNG格式
    image_b64 = base64.b64encode(img).decode('utf-8')  # 将图片转化为base64编码格式

    len_of_project = len(cmodels.data.objects.filter(taskId_id=int(taskId)))
    len_of_label = len(wmodels.labels.objects.filter(taskId_id=int(taskId)))
    progress = '{:.2f}%'.format(len_of_label / len_of_project * 100)

    task = cmodels.task.objects.get(taskId=taskId)
    if len(wmodels.labels.objects.filter(lId=true_id)) != 0:
        print("已经经过标注")
        label = wmodels.labels.objects.get(lId=true_id)
        context = {'project_id': taskId,
                   'true_id': true_id,
                   "progress": progress,
                   "len_of_label": str(len_of_label),
                   "label": label.label,
                   "task_type": str(task.taskType),
                   'image_b64': image_b64}
        json_data = json.dumps(context)

        return HttpResponse(json_data, content_type='application/json')
    else:
        print("未经过标注")
        context = {'project_id': taskId,
                   'true_id': true_id,
                   "progress": progress,
                   "len_of_label": str(len_of_label),
                   "label": False,
                   "task_type": str(task.taskType),
                   'image_b64': image_b64}
        json_data = json.dumps(context)
        return HttpResponse(json_data, content_type='application/json')

templates/service/task_list.html
{#<!doctype html>#}
{% extends "service/base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block links %}
        {{ block.super }}
        <title>全部待处理任务</title>
    {% endblock %}
</head>
<body>

    <div class="container-scroller">
      <!-- partial:partials/_navbar.html -->
      {% block navbar %}
          {{ block.super }}
      {% endblock %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        {% block sidebar %}
            {{ block.super }}
            <div class="main-panel">
            <div class="content-wrapper">
                <div class="page-header">
                  <h3 class="page-title">
                    <span class="page-title-icon bg-gradient-primary text-white me-2">
                      <i class="mdi mdi-home"></i>
                    </span> 全部任务
                  </h3>
                  <nav aria-label="breadcrumb">
                    <ul class="breadcrumb">
                      <li class="breadcrumb-item active" aria-current="page">
                        <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
                      </li>
                    </ul>
                  </nav>
                </div>
                <div class="row">
                    <div class="col-12 grid-margin">
                        <div class="card">
                          <div class="card-body">
                            <!--设置下拉选择框，选择任务类型，包括全部任务，待发布任务，申诉任务-->
                            <div class="dropdown mb-3 dropend taskType">
                                <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown">
                                  任务类型选择
                                </button>
                                <ul class="dropdown-menu" id="types">
                                  <li><a class="dropdown-item active type" href="#" id="type1">全部任务</a></li>
                                  <li><a class="dropdown-item type" href="#" id="type2">待发布任务( {{ rctask|length }} )</a></li>
                                  <li><a class="dropdown-item type" href="#" id="type3">申诉任务( {{ problem|length }} )</a></li>
                                </ul>
                            </div>
                              <script>
                                  $('#types').find('a').each(function () {
                                    $(this).click(function () {
                                        $(this).parent().siblings().find('a').removeClass("active")
                                        $(this).addClass('active')
                                        // 调整页面显示内容
                                        const s = "my"+this.id
                                        const section = document.getElementById(s)
                                        const sections = document.getElementsByClassName('mytype')
                                        for (each of sections){
                                            $(each).addClass('visually-hidden')
                                        }
                                        $(section).removeClass('visually-hidden')
                                        // 或者写成一句
                                        //$(this).parent().addClass('active').siblings().removeClass("active")
                                    })
                                })
                              </script>
                            <div class="table-responsive mytype" id="mytype1">
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th> 任务ID </th>
                                    <th> 任务名称 </th>
                                    <th> 任务内容 </th>
                                    <th> 任务类型 </th>
                                    <th> 任务状态 </th>
                                    <th> 发起人 </th>
                                    <th> 创建时间 </th>
                                  </tr>
                                </thead>
                                <tbody>
                                    {% for item in taskAll %}
                                        {% if item.type == "rctask" %}
                                            <tr>
                                                <td><a class="nav-link" href="/service/{{ sId }}/{{ item.taskId_id }}/check?type=rctask">{{ item.taskId_id }}</a></td>
                                                <td><a class="nav-link" href="/service/{{ sId }}/{{ item.taskId_id }}/check?type=rctask">{{ item.taskName }}</a></td>
                                                <td>{{ item.taskContent }}</td>
                                                <td>{{ item.taskType }}</td>
                                                <td>{{ item.status }}</td>
                                                <td>{{ item.cName }}</td>
                                                <td>{{ item.subTime }}</td>
                                                <td>待发布任务</td>
                                            </tr>
                                        {% elif item.type == "problem" %}
                                            <tr>
                                                <td><a class="nav-link" href="/service/{{ sId }}/{{ item.pId }}/handle?type=problem">{{ item.pId }}</a></td>
                                                <td><a class="nav-link" href="/service/{{ sId }}/{{ item.pId }}/handle?type=problem">{{ item.pName }}</a></td>
                                                <td>{{ item.pContent }}</td>
                                                <td>{{ item.get_type_display }}</td>
                                                <td>{{ item.get_status_display }}</td>
                                                <td>{{ item.name }}</td>
                                                <td>{{ item.subTime }}</td>
                                                <td>申诉任务</td>
                                            </tr>
                                        {% endif %}
                                    {% endfor %}
                                </tbody>
                              </table>
                            </div>

                            <div class="table-responsive mytype visually-hidden" id="mytype2">
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th> 任务ID </th>
                                    <th> 任务名称 </th>
                                    <th> 任务内容 </th>
                                    <th> 任务限制 </th>
                                    <th> 任务类型 </th>
                                    <th> 任务状态 </th>
                                    <th> 创建时间 </th>
                                  </tr>
                                </thead>
                                <tbody>
                                    {% for item in rctask %}
                                        <tr>
                                            <td><a class="nav-link" href="/service/{{ sId }}/{{ item.taskId_id }}/check?type=rctask">{{ item.taskId_id }}</a></td>
                                            <td><a class="nav-link" href="/service/{{ sId }}/{{ item.taskId_id }}/check?type=rctask">{{ item.taskName }}</a></td>
                                            <td>{{ item.taskContent }}</td>
                                            <td>{{ item.taskLimit }}</td>
                                            <td>{{ item.taskType }}</td>
                                            <td>{{ item.status }}</td>
                                            <td>{{ item.subTime }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                              </table>
                            </div>

                            <div class="table-responsive mytype visually-hidden" id="mytype3">
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th> 任务ID </th>
                                    <th> 任务名称 </th>
                                    <th> 任务类型 </th>
                                    <th> 任务内容 </th>
                                    <th> 相关标注任务 </th>
                                    <th> 任务状态 </th>
                                    <th> 创建时间 </th>
                                  </tr>
                                </thead>
                                <tbody>
                                    {% for item in problem %}
                                        <tr>
                                            <td><a class="nav-link" href="/service/{{ sId }}/{{ item.pId }}/handle?type=problem">{{ item.pId }}</a></td>
                                            <td><a class="nav-link" href="/service/{{ sId }}/{{ item.pId }}/handle?type=problem">{{ item.pName }}</a></td>
                                            <td>{{ item.get_type_display }}</td>
                                            <td>{{ item.pContent }}</td>
                                            <td><a class="nav-link" href="/service/{{ sId }}/{{ item.taskId_id }}/handle?type=rctask">{{ item.taskId_id }}</a></td>
                                            <td>{{ item.get_status_display }}</td>
                                            <td>{{ item.subTime }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                              </table>
                            </div>

                          </div>
                        </div>
                      </div>
                </div>
          </div>
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->
          <footer class="footer">
            <div class="container-fluid d-flex justify-content-between">
              <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © bootstrapdash.com 2021</span>
              <span class="float-none float-sm-end mt-1 mt-sm-0 text-end"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin template</a> from Bootstrapdash.com</span>
            </div>
          </footer>
          <!-- partial -->
        </div>
        <!-- partial -->
        {% endblock %}
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    {% block script %}
        {{ block.super }}
    {% endblock %}
</body>
</html>