datalabel/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='login'),
    path('index', views.index, name='login'),
    path('notice', views.notice, name='notice'),
    path('jiaocheng', views.jiaocheng, name='jiaocheng'),
    path('task_detail', views.task_detail, name='task_detail'),
    path('notice_info', views.notice_info, name='notice_info'),
    path('login', views.login, name='login'),
    path('admin_login', views.admin_login, name='admin_login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('comment', views.comment, name='comment'),
    path('creator/', include('creator.urls')),
    path('worker/', include('worker.urls')),
    path('service/', include('service.urls')),
    path('finance/', include('finance.urls')),
    path('manager/', include('manager.urls')),
    path('admin/', admin.site.urls),
]

worker/urls.py
from django.urls import path
from . import views
from . import admin
app_name='worker'

urlpatterns = [
	path('<str:name>/', views.index, name="index"),
	# path('index', views.index, name='index'),
	path('<str:name>/index', views.index, name='index'),
	path('<str:name>/info', views.info, name='info'),
	path('<str:name>/task_list', views.task_list, name='task_list'),
	path('<str:name>/charts', views.charts, name='charts'),
	path('<str:name>/other_info', views.other_info, name="other_info"),
	path('<str:name>/task_info', views.task_info, name="task_info"),
	path('<str:name>/task_accept', views.task_accept, name="task_accept"),
	path('<str:name>/task_submit', views.task_submit, name="task_submit"),
	path('<str:name>/task_abandon', views.task_abandon, name="task_abandon"),
	path('<str:name>/labelTry', views.labelTry, name="labelTry"),
	path('<str:name>/problem_create', views.problem_create, name="problem_create"),
	path('<str:name>/label', views.label, name="label"),
	path('<str:name>/getlink/', views.getlink),
]

creator/models.py
import datetime

from django.db import models
# Create your models here.

class creator(models.Model):
    cId = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    email = models.EmailField()
    phone = models.CharField(max_length=11)
    pwd = models.CharField(max_length=16)
    point = models.IntegerField(default = 0)

class task(models.Model):
    taskId = models.AutoField(primary_key=True)
    taskName = models.CharField(max_length=200, default=None)
    cover = models.BinaryField(null=True)
    cId = models.ForeignKey(creator, to_field='cId', on_delete=models.CASCADE)
    taskContent = models.TextField()
    taskDescription = models.BinaryField(null=True)
    createTime = models.DateTimeField(null=True)
    types = (
        ('textClean', '文本清洗'),
        ('emotionLable', '情感标注'),
        ('textClass', '文本分类'),
        ('semanticSeg', '语义分割'),
        ('picClass', '图片分类'),
        ('objectDetection', '目标检测')
    )
    taskType = models.CharField(choices=types, max_length=20)
    taskLimit = models.DateTimeField(max_length=20)
    deleted = models.BooleanField(default=False)
    reward = models.CharField(max_length=20, default=0)
    statuss = (
        ('rChecking', '发布审核中'),
        ('unpass', '审核未通过'),
        ('unAccept', '未被接受'),
        ('labeling', '标注中'),
        ('checking', '审核中'),
        ('over', '已完成'),
        ('cancel', '已取消'),
    )
    status = models.CharField(choices=statuss, default='rChecking', max_length=20)
    lastUpdate = models.DateTimeField(default='2023-05-01 00:00:00')

class data(models.Model):
    types = (
        ('word', '文字'),
        ('pic', '图片'),
        ('video', '视频')
    )
    dId = models.AutoField(primary_key=True)
    dLink = models.URLField(max_length=100, null=True)
    dType = models.CharField(choices=types, max_length=20)
    dFile = models.BinaryField(null=True)
    taskId = models.ForeignKey(task, to_field='taskId', on_delete=models.CASCADE, null=True)
    description = models.TextField(null=True)


class checkTask(models.Model):
    checkId = models.AutoField(primary_key=True)
    cId = models.ForeignKey(creator, to_field='cId', on_delete=models.CASCADE)
    taskId = models.ForeignKey(task, to_field="taskId", on_delete=models.CASCADE)
    subTime = models.DateTimeField()
    results = (
        ('good', '优质'),
        ('pass', '通过'),
        ('low', '低质'),
        ('unpass', '未通过')
    )
    checkResult = models.CharField(choices=results, null=True, max_length=20)
    finTime = models.DateTimeField(default=None, null=True)
    type = (
        ('labelTryCheck', '试标注审核'),
        ('labelCheck', '标注审核')
    )
    checkType = models.CharField(choices=type, max_length=20)

class problem(models.Model):
    cpId = models.AutoField(primary_key=True)
    pName = models.CharField(max_length=40, null=True)
    cId = models.ForeignKey(creator, related_name="p_cId", to_field="cId", on_delete=models.CASCADE)
    taskId = models.ForeignKey(task, to_field="taskId", related_name="cproblem_taskId", on_delete=models.CASCADE, null=True)
    pContent = models.TextField()
    subTime = models.DateTimeField()
    types = (
        ('taskResult', "任务审核结果申诉"),
        ('taskReward', "任务奖励发放申诉"),
        ('account', "个人账户信息申诉"),
        ('labelSystem', "标注系统异常申诉"),
    )
    type = models.CharField(choices=types, null=True, max_length=20)
    statuss = (
        ('unHandle', '未处理'),
        ('handled', '已处理')
    )
    status = models.CharField(choices=statuss, max_length=20)
    feedBack = models.TextField(null=True)
    finTime = models.DateTimeField(null=True)



templates/admin_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>数据标注众包平台-管理人员登录界面</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="/statics/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/statics/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="/statics/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="/statics/images/favicon.ico" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
          <div class="row flex-grow">
            <div class="col-lg-4 mx-auto">
              <div class="auth-form-light text-left p-5">
                <h4 class="text-center">数据标注众包平台</h4>
{#                <h6 class="font-weight-light">Sign in to continue.</h6>#}
                <form class="pt-3" action="admin_login" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <input type="text" class="form-control form-control-lg" id="exampleInputEmail1" placeholder="staffId" name="id">
                  </div>
                  <div class="form-group mt-3">
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="pwd">
                    <p class="text-center">{{ msg }}</p>
                  </div>
                  <div class="form-group mb-3 mt-3">
                    <select class="form-control form-control-lg" id="exampleInputEmail1" placeholder="userType" name="type">
                        <option value="servicer">servicer</option>
                        <option value="financer">financer</option>
                        <option value="manager">manager</option>
                    </select>
                  </div>
                  <div class="mt-3 text-center">
{#                    <a class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn" href="/statics/index.html">SIGN IN</a>#}
                      <button class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn" type="submit">登录</button>
                  </div>
                </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="/statics/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="/statics/js/off-canvas.js"></script>
    <script src="/statics/js/hoverable-collapse.js"></script>
    <script src="/statics/js/misc.js"></script>
    <!-- endinject -->
  </body>
</html>

templates/error-404.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="../../assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End Plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="../../assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="../../assets/images/favicon.ico" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
          <div class="row flex-grow">
            <div class="col-lg-7 mx-auto text-white">
              <div class="row align-items-center d-flex flex-row">
                <div class="col-lg-6 text-lg-right pr-lg-4">
                  <h1 class="display-1 mb-0">404</h1>
                </div>
                <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
                  <h2>SORRY!</h2>
                  <h3 class="font-weight-light">The page you’re looking for was not found.</h3>
                  <h3>{{ msg}}</h3>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 text-center mt-xl-2">
                  <a class="text-white font-weight-medium" href="../../index.html">Back to home</a>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 mt-xl-2">
                  <p class="text-white font-weight-medium text-center">Copyright &copy; 2021 All rights reserved.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="../../assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="../../assets/js/off-canvas.js"></script>
    <script src="../../assets/js/hoverable-collapse.js"></script>
    <script src="../../assets/js/misc.js"></script>
    <!-- endinject -->
  </body>
</html>

templates/error-500.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="../../assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End Plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="../../assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="../../assets/images/favicon.ico" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center text-center error-page bg-info">
          <div class="row flex-grow">
            <div class="col-lg-7 mx-auto text-white">
              <div class="row align-items-center d-flex flex-row">
                <div class="col-lg-6 text-lg-right pr-lg-4">
                  <h1 class="display-1 mb-0">500</h1>
                </div>
                <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
                  <h2>SORRY!</h2>
                  <h3 class="font-weight-light">Internal server error!</h3>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 text-center mt-xl-2">
                  <a class="text-white font-weight-medium" href="../../index.html">Back to home</a>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 mt-xl-2">
                  <p class="text-white font-weight-medium text-center">Copyright &copy; 2021 All rights reserved.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="../../assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="../../assets/js/off-canvas.js"></script>
    <script src="../../assets/js/hoverable-collapse.js"></script>
    <script src="../../assets/js/misc.js"></script>
    <!-- endinject -->
  </body>
</html>

templates/task_detail.html

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>数据标注众包平台</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="/statics/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/statics/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="/statics/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="/statics/images/favicon.ico" />
    <link rel="stylesheet" href="/statics/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="/statics/css/bootstrap.css">
    <script type="text/javascript" src="/statics/js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="/statics/js/bootstrap.min.js"></script>
    <script src="/statics/js/pdfobject.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.11.338/pdf.min.js"></script>
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <!-- End layout styles -->
    <link rel="stylesheet" href="/statics/css/bootstrap-datetimepicker.min.css">
      <style>
          #navbarNav > ul > li{
              margin-left: 2rem;
              margin-right: 2rem;
          }
          #navbar{
              line-height: 2rem;
          }
          #tasks .img-box{
              overflow: hidden;
          }
          #tasks .img-box > img{
              height: 18rem;
              width: 17rem;
              background-color: black;
          }
          #tasks > li{
              margin-right: 1.39rem;
              margin-bottom: 2rem;
          }
      </style>
  </head>
  <body>
      <div class="container-scroller bg-body-secondary">
          <nav class="navbar navbar-expand-md navbar-dark bg-dark" id="navbar">
              <div class="bg-dark text-center navbar-brand-wrapper d-flex align-items-center justify-content-center" style="width: 2rem;height: 1.2rem;margin-left: 5rem;margin-right: 16rem">
                 <a class="navbar-brand text-light" href="#">
                 </a>
              </div>
                &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
              <button class="navbar-toggler btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon icon-sm"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto fs-6">
                  <li class="nav-item">
                    <a class="nav-link active s" href="/index" id="s1">首页</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link s" href="/notice" id="s2">公告</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link s" href="/jiaocheng" id="s3">使用说明</a>
                  </li>
                </ul>
              </div>
              <div class="collapse navbar-collapse text-center">
                  {% if not name %}
                      <p class="text-light mb-0">欢迎，请
                          <a class="text-decoration-none text-primary" href="/login">登录</a>&ensp;
                          <a class="text-decoration-none " href="/register">注册</a>
                      </p>
                  {% elif name %}
                      <div class="text-light">
                          <div class="dropdown" aria-labelledby="profileDropdown">
                            <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown">
                                {{ type }}:{{ name }}
                            </button>
                            <ul class="dropdown-menu">
                                <a class="dropdown-item" href="/{{ type }}/{{ name }}/">
                                  <i class="mdi mdi-cached me-2 text-success"></i>个人中心</a>
                                <a class="dropdown-item" href="/logout">
                                  <i class="mdi mdi-logout me-2 text-primary"></i>退出</a>
                            </ul>
                          </div>
                      </div>
                  {% endif %}
              </div>
              <script>
                  //给当前元素设置新的样式，并删除当前元素的同胞元素的样式
                 $('#navbarNav').find('a').each(function () {
                        $(this).click(function () {
                            $(this).parent().siblings().find('a').removeClass("active")
                            $(this).addClass('active')
                            // 调整页面显示内容
                            const s = "my"+this.id
                            console.log(s)
                            const section = document.getElementById(s)
                            const sections = document.getElementsByClassName('mysection')
                            for (each of sections){
                                $(each).addClass('visually-hidden')
                            }
                            $(section).removeClass('visually-hidden')
                            section.style.display='block';
                            // 或者写成一句
                            //$(this).parent().addClass('active').siblings().removeClass("active")
                        })
                    })
              </script>

          </nav>
          <div class="main-panel">
              <div class="row mt-4">
                  <div class="row mysection" id="mys1" style="margin-left: 9.3rem">
                        <div class="col-12 bg-white align-items-center"  style="width: 98.3%">
                            <div class="row mt-2" style="margin-left: 1rem">
                                <div class="fs-4">{{ task.taskName }}</div>
                            </div>
                            <div class="text-warning mt-2" style="margin-left: 2rem">库位标注任务质检，需要每天完成固定任务量。详细工作内容报名通过后沟通</div>
                            <div class="row mt-3 justify-content-center mb-4 fs-1" style="margin-left: 2rem; width: 96%">
                                <div class="bg-body-secondary">
                                    <table class="table table-borderless mt-2">
                                        <tr>
                                            <td>任务类型：&ensp;<strong>{{ task.get_taskType_display }}</strong></td>
                                            <td>任务发布时间：&ensp;<strong>{{ task.createTime }}</strong></td>
                                            <td>任务量：&ensp;<strong>1000{{ task.size }}</strong></td>
                                            <td>任务截止时间：&ensp;<strong>{{ task.taskLimit }}</strong></td>
                                        </tr>
                                        <tr>
                                            <td>任务发布者：&ensp;<strong>{{ task.cId_id }}</strong></td>
                                            <td>任务奖励：&ensp;<strong>{{ task.reward }} 积分</strong></td>
                                            <td>任务内容：&ensp;<strong>{{ task.taskContent }}</strong></td>
                                        </tr>
                                    </table>

                                </div>
                            </div>
                            <div style="margin-left: 2rem; width: 96%">
                                <div><strong>| 任务需求</strong></div>
                                {% if type == 'worker' and task.status == "unAccept" %}
                                    <div class="mt-3 d-inline-block">
                                    <a class="nav-link text-bg-warning" href="/worker/{{ name }}/labelTry?taskId={{ task.taskId }}">
                                        <button class="btn btn-warning">
                                            进行试标注
                                        </button>
                                    </a>
                                    </div>
                                    <div class="mt-3 d-inline-block" style="">
                                    <a class="nav-link" href="/worker/{{ name }}/task_accept?taskId={{ task.taskId }}">
                                        <button class="btn btn-success">
                                            接受任务</a>
                                        </button>
                                    </div>
                                    </div>
                                {% endif %}
                                <div id="pdfContainer" class="border-2 mt-2 mb-4" style="margin-top: 0px;height: 600px;"></div>
                                    <script>
                                        const pdfdata = "{{ task.taskDescription }}"; // 替换为实际的PDF文件路径
                                        /*
                                        var url = "/statics/images/test任务需求.pdf"
                                        {#const loadingTask = pdfjsLib.getDocument({data: pdfdata});#}
                                        const loadingTask = pdfjsLib.getDocument(url)
                                        pdfjsLib.getDocument(url).promise.then(function(pdf) {
                                          var numPages = pdf.numPages;  // 获取PDF的总页数
                                          var pdfContainer = document.getElementById('pdfContainer');

                                          // 遍历每一页，创建并渲染canvas
                                          for (var pageNum = 1; pageNum <= numPages; pageNum++) {
                                            pdf.getPage(pageNum).then(function(page) {
                                              var canvas = document.createElement('canvas');
                                              var context = canvas.getContext('2d');
                                              var viewport = page.getViewport({ scale: 1.5 });
                                              canvas.width = viewport.width;
                                              canvas.height = viewport.height;

                                              // 将canvas添加到页面中的容器
                                              pdfContainer.appendChild(canvas);

                                              // 渲染当前页到canvas
                                              page.render({
                                                canvasContext: context,
                                                viewport: viewport
                                              });
                                            });
                                          }
                                        });
                                        */
                                            // 将 PDF 文件的二进制数据转换为可加载的 URL
                                        function createObjectURL(data) {
                                          var blob = new Blob([data], { type: 'application/pdf' });
                                          return URL.createObjectURL(blob);
                                        }

                                        // 在指定的容器中嵌入 PDF 文件
                                        var options = {
                                          fallbackLink: '<p>This browser does not support PDFs. <a href="#">Download the PDF</a> to view it.</p>'
                                        };

                                        // 假设你从后端获取到了 PDF 文件的二进制数据，存储在变量 binaryData 中
                                        // 使用 createObjectURL 方法将二进制数据转换为可加载的 URL
                                        var binaryData = "{{ task.taskDescription }}"; // 替换为实际的 PDF 文件的二进制数据
                                        var pdfURL = createObjectURL(binaryData);
                                        pdfURL = "/statics/temp/{{ task.taskName }}.pdf"
                                        {#pdfURL = "{{ task.taskDescriptionPath }}"#}
                                        // 嵌入 PDF 文件
                                        console.log(pdfURL)
                                        PDFObject.embed(pdfURL, '#pdfContainer', options);
                                    </script>
                                </div>
                          </div>
                        </div>
                   </div>
              </div>
          </div>
        </div>
    <script src="/statics/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="/statics/vendors/chart.js/Chart.min.js"></script>
    <script src="/statics/js/jquery.cookie.js" type="text/javascript"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="/statics/js/off-canvas.js"></script>
    <script src="/statics/js/hoverable-collapse.js"></script>
    <script src="/statics/js/misc.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="/statics/js/dashboard.js"></script>
    <script src="/statics/js/todolist.js"></script>
    <!-- End custom js for this page -->
  </body>
</html>